function Symb_B_P = B_eq_P(in1)
%B_eq_P
%    Symb_B_P = B_eq_P(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    09-Jan-2026 11:17:09

q2 = in1(:,2);
t2 = cos(q2);
t3 = t2.^2;
t4 = t2.*3.727273059851063e+40;
t5 = t3.*1.753488156460813e+40;
t6 = t4+2.495374801782695e+40;
t7 = t5-3.133832864384994e+40;
t8 = 1.0./t7;
t9 = t6.*t8;
Symb_B_P = reshape([0.0,0.0,t8.*-2.495374801782695e+40,t9,0.0,0.0,t9,-t8.*(t2.*7.454546119702126e+40+1.244529572326752e+41)],[4,2]);
end
