function Symb_C_WP = C_eq_WP(in1)
%C_eq_WP
%    Symb_C_WP = C_eq_WP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    09-Jan-2026 11:29:58

Symb_C_WP = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],[2,4]);
end
