function Symb_C_P = C_eq_P(in1,in2)
%C_eq_P
%    Symb_C_P = C_eq_P(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    28-Jan-2026 12:16:16

Symb_C_P = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],[2,4]);
end
