function Symb_C_WP = C_eq_WP(in1,in2)
%C_eq_WP
%    Symb_C_WP = C_eq_WP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Jan-2026 17:13:55

Symb_C_WP = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],[2,4]);
end
