function Symb_D_WP = D_eq_WP(in1)
%D_eq_WP
%    Symb_D_WP = D_eq_WP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    09-Jan-2026 11:17:40

Symb_D_WP = reshape([0.0,0.0,0.0,0.0],[2,2]);
end
