function Symb_D_P = D_eq_P(in1)
%D_eq_P
%    Symb_D_P = D_eq_P(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    09-Jan-2026 11:17:10

Symb_D_P = reshape([0.0,0.0,0.0,0.0],[2,2]);
end
