function Symb_D_WP = D_eq_WP(in1,in2)
%D_eq_WP
%    Symb_D_WP = D_eq_WP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    28-Jan-2026 12:16:37

Symb_D_WP = reshape([0.0,0.0,0.0,0.0],[2,2]);
end
