function Symb_D_P = D_eq_P(in1,in2)
%D_eq_P
%    Symb_D_P = D_eq_P(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Jan-2026 17:13:38

Symb_D_P = reshape([0.0,0.0,0.0,0.0],[2,2]);
end
